def profession():
    return [
        "Cardiology",
        "Pediatrics",
        "Gynecology",
        "Ophthalmology",
        "Dermatology"
    ]

def diagnosis():
    return [
        "Common cold",
        "Throat infection",
        "Wrist fracture",
        "Appendicitis",
        "Type 2 diabetes",
        "High blood pressure",
        "Asthma",
        "Acute bronchitis",
        "Pneumonia",
        "Back pain",
        "Arthritis",
        "Gastritis",
        "Peptic ulcer",
        "Hepatitis",
        "Cholecystitis",
        "Insomnia",
        "Depression",
        "Anxiety",
        "Panic disorder",
        "Obsessive-compulsive disorder",
        "Schizophrenia",
        "Bipolar disorder",
        "Post-traumatic stress disorder",
        "Borderline personality disorder",
        "Attention deficit hyperactivity disorder (ADHD)",
        "Epilepsy",
        "Migraine",
        "Tension headache",
        "Alzheimer_s disease",
        "Parkinson_s disease",
        "Multiple sclerosis",
        "Systemic lupus erythematosus",
        "Rheumatoid arthritis",
        "Chronic obstructive pulmonary disease (COPD)",
        "Bronchial asthma",
        "Lung cancer",
        "Breast cancer",
        "Prostate cancer",
        "Colorectal cancer",
        "Skin cancer",
        "Thyroid cancer",
        "Ovarian cancer",
        "Uterine cancer",
        "Pancreatic cancer",
        "Liver cancer",
        "Kidney cancer",
        "Leukemia",
        "Lymphoma",
        "Hodgkin_s disease",
        "Amyotrophic lateral sclerosis (ALS)",
        "Heart attack",
        "Heart failure",
        "Heart arrhythmia",
        "Pulmonary hypertension",
        "Deep vein thrombosis",
        "Pulmonary embolism",
        "Kidney failure",
        "Diabetic nephropathy",
        "Kidney stones",
        "Glomerulonephritis",
        "Urinary tract infection",
        "Prostatitis",
        "Benign prostatic hyperplasia (BPH)",
        "Crohn_s disease",
        "Ulcerative colitis",
        "Pancratitis",
        "Diverticulitis",
        "Herniated disc",
        "Scoliosis",
        "Carpal tunnel syndrome",
        "Fibromyalgia",
        "Peripheral artery disease (PAD)",
        "Venous ulcer ",
        "Diabetic foot ",
        "Varicose veins ",
        "Anemia ",
        "Leukopenia ",
        "Thrombocytopenia ",
        "Thrombocytosis ",
        "Hemophilia ",
        "Leukemia ",
        "Lymphoma ",
        "Multiple myeloma ",
        "Hodgkin lymphoma ",
        "Ankylosing spondylitis ",
        "Psoriatic arthritis ",
        "Gout ",
        "Osteoporosis ",
        "Osteoarthritis ",
        "Tendinitis ",
        "Bursitis ",
        "Conjunctivitis ",
        "Glaucoma ",
        "Cataracts ",
        "Macular degeneration ",
        "Retinal detachment ",
        "Strabismus ",
        "Common cold ",
        "Sinusitis ",
        "Pharyngitis ",
        "Laryngitis ",
        "Tonsillitis "
    ]

def treatment():
    return [
        "Antibiotics",
        "Analgesics",
        "Anti-inflammatory drugs",
        "Antipyretics",
        "Antivirals",
        "Corticosteroids",
        "Antihistamines",
        "Bronchodilators",
        "Expectorants",
        "Mucolytics",
        "Antitussives",
        "Decongestants",
        "Antidiarrheals",
        "Antiulcer drugs",
        "Antiemetics",
        "Laxatives",
        "Antifungals",
        "Antiparasitics",
        "Antimycotics",
        "Topical antivirals",
        "Topical corticosteroids",
        "Topical anesthetics",
        "Keratolytics",
        "Emollients",
        "Acne treatments",
        "Cellulite treatments",
        "Anti-stretch mark treatments",
        "Anti-lice treatments",
        "Insect repellents",
        "Sunscreen",
        "Moisturizers",
        "Skin lotions",
        "Skin creams",
        "Skin gels",
        "Skin ointments",
        "Eye drops",
        "Ear drops",
        "Nasal irrigation solutions",
        "Dental creams",
        "Mouthwashes",
        "Throat lozenges",
        "Cough drops",
        "Fever reducers",
        "Pain relievers",
        "Anti-inflammatory pills",
        "Stomach ache pills",
        "Diarrhea pills",
        "Acid reflux pills",
        "Nausea pills",
        "Constipation pills",
        "Dizziness pills",
        "Sleep aids",
        "Anxiety pills",
        "Depression pills",
        "Asthma pills",
        "Allergy pills",
        "Cold pills",
        "Flu pills",
        "Bronchitis pills",
        "Pneumonia pills",
        "Arthritis pills",
        "Gastritis pills",
        "Ulcer pills",
        "Cholesterol pills",
        "Diabetes pills",
        "High blood pressure pills",
        "Heart disease pills",
        "Kidney disease pills",
        "Liver disease pills",
        "Lung disease pills",
        "Thyroid disease pills",
        "Intestinal disease pills",
        "Bone disease pills",
        "Joint disease pills",
        "Eye disease pills",
        "Dental disease pills",
        "Ear disease pills",
        "Skin disease pills",
        "Hair disease pills",
        "Nail disease pills",
        "Genital disease pills",
        "Sexual disease pills",
        "Mental disease pills",
        "Neurological disease pills",
        "Psychological disease pills",
        "Emotional disease pills",
        "Psychiatric disease pills",
        "Sleep disorder pills",
        "Appetite disorder pills",
        "Memory disorder pills",
        "Concentration disorder pills",
        "Attention disorder pills",
        "Learning disorder pills",
        "Development disorder pills",
        "Growth disorder pills",
        "Aging disorder pills",
        "Pregnancy disorder pills",
        "Childbirth disorder pills",
        "Postpartum disorder pills",
        "Breastfeeding disorder pills",
        "Infant disorder pills",
        "Child disorder pills",
        "Adolescent disorder pills",
        "Adult disorder pills",
        "Elderly disorder pills",
        "Male disorder pills",
        "Female disorder pills",
        "Couple disorder pills",
        "Family disorder pills",
        "Community disorder pills",
        "Society disorder pills",
        "Humanity disorder pills",
        "Earth disorder pills",
        "Universe disorder pills",
        "Infinity disorder pills",
        "Afterlife disorder pills",
        "This life disorder pills",
        "Divine disorder pills",
        "Human disorder pills",
        "Terrestrial disorder pills",
        "Celestial disorder pills",
        "Spiritual disorder pills",
        "Material disorder pills",
        "Ethereal disorder pills",
        "Corporeal disorder pills",
        "Incorporeal disorder pills",
        "Visible disorder pills",
        "Invisible disorder pills",
        "Tangible disorder pills",
        "Intangible disorder pills",
        "Finite disorder pills",
        "Infinite disorder pills",
        "Relative disorder pills",
        "Absolute disorder pills",
        "Concrete disorder pills",
        "Abstract disorder pills",
        "Objective disorder pills",
        "Subjective disorder pills",
        "Real disorder pills",
        "Unreal disorder pills",
        "Imaginary disorder pills",
        "True disorder pills",
        "False disorder pills"
    ]

def test_result():
    return [
        "Negative",
        "Positive",
        "Inconclusive",
        "Abnormal",
        "Normal",
        "Elevated",
        "Low",
        "High",
        "Moderate",
        "Severe",
        "Mild",
        "Inflamed",
        "Infected",
        "Mild inflammation",
        "Moderate inflammation",
        "Severe inflammation",
        "Bacteria present",
        "No bacteria",
        "Bacterial infection",
        "Viral infection",
        "Fungal infection",
        "Parasitic infection",
        "Chronic inflammation",
        "Acute inflammation",
        "Blood clots present",
        "No blood clots",
        "Tumor detected",
        "No tumor",
        "Injury present",
        "No injury",
        "Fracture detected",
        "No fracture",
        "Anomalies detected",
        "No anomalies",
        "Structural changes",
        "No structural changes",
        "Normal kidney function",
        "Abnormal kidney function",
        "Normal liver function",
        "Abnormal liver function",
        "Normal heart function",
        "Abnormal heart function",
        "Normal lung function",
        "Abnormal lung function",
        "Normal thyroid function",
        "Abnormal thyroid function",
        "Normal pancreatic function",
        "Abnormal pancreatic function",
        "Normal intestinal function",
        "Abnormal intestinal function",
        "Normal blood pressure",
        "High blood pressure",
        "Low blood pressure",
        "Normal blood sugar level",
        "High blood sugar level",
        "Low blood sugar level",
        "Normal cholesterol level",
        "High cholesterol level",
        "Low cholesterol level",
        "Normal triglyceride level",
        "High triglyceride level",
        "Low triglyceride level",
        "Normal hemoglobin level",
        "High hemoglobin level",
        "Low hemoglobin level",
        "Normal white blood cell count",
        "High white blood cell count",
        "Low white blood cell count",
        "Normal red blood cell count",
        "High red blood cell count",
        "Low red blood cell count",
        "Normal platelet count",
        "High platelet count",
        "Low platelet count",
        "Normal X-ray result",
        "Abnormal X-ray result",
        "Normal CT scan result",
        "Abnormal CT scan result",
        "Normal MRI result",
        "Abnormal MRI result",
        "Normal ultrasound result",
        "Abnormal ultrasound result",
        "Normal endoscopy result",
        "Abnormal endoscopy result",
        "Normal colonoscopy result",
        "Abnormal colonoscopy result",
        "Normal stress test result",
        "Abnormal stress test result",
        "Positive allergy test",
        "Negative allergy test",
        "Normal glucose tolerance test",
        "Abnormal glucose tolerance test",
        "Normal lung function test",
        "Abnormal lung function test",
        "Normal kidney function test",
        "Abnormal kidney function test",
        "Normal liver function test",
        "Abnormal liver function test",
        "Normal thyroid function test",
        "Abnormal thyroid function test",
        "Normal cardiac stress test",
        "Abnormal cardiac stress test",
        "Normal blood glucose test",
        "High blood glucose test",
        "Low blood glucose test",
        "Normal blood pressure test",
        "High blood pressure test",
        "Low blood pressure test",
        "Normal cardiac function test",
        "Abnormal cardiac function test",
        "Normal intestinal function test",
        "Abnormal intestinal function test"
    ]

def gender():
    return [
        "Male",
        "Female"
    ]
